import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { bridgeApi } from "../../api/bridge";
import { Button } from "../ui/button";
import { copyToClipboard } from "../../lib/clipboard";
import { timeAgo } from "../../lib/timeAgo";

/**
 * Talking to your agent from Claude Code or Codex, set up on this page.
 *
 * This replaces the separate connect-a-machine guide. That page put the only
 * route to a working connection one click away from the page it belongs to,
 * and split the explanation from the thing being explained.
 *
 * The shape here is deliberate and bounded by what actually exists:
 *
 *  - The connection key is generated by a button. That is the existing bridge
 *    enrolment — request, then approve, both owned by the signed-in steward —
 *    so no new credential type and no widening of authority.
 *  - There is exactly ONE thing to paste, once. Writing the key and creating
 *    the folder used to be two commands plus a visible token to handle by
 *    hand; they are one line here because `inbox-init` already accepts both
 *    `--server` and `--token-file`.
 *  - Nothing after that. No config file to edit, no API key, no second
 *    command, nothing to leave running.
 *
 * The name of the CLI is `paperclipai` because that is the bin the package
 * declares and a test pins it. The installer also puts `agentdash` on PATH,
 * but the guard exists because an unrelated package owns `agentdash` on npm,
 * so this prints the one that is certain to be the right program.
 */
export const CONNECT_CLI_BIN = "paperclipai";
export const INBOX_DIR = "~/agentdash-inbox";
const TOKEN_PATH = "~/.agentdash/bridge-token";

/**
 * One line, and the reason it is one line rather than three.
 *
 * `resolveToken` has no default file location — it reads `--token-file` or the
 * `AGENTDASH_BRIDGE_TOKEN` environment variable and otherwise refuses to
 * start. So the key has to be written somewhere and that path has to be handed
 * to `inbox-init`, which bakes it into the hook it installs. Chaining with
 * `&&` means a failure stops rather than continuing to a half-built setup.
 */
export function buildSetupLine(key: string, origin: string): string {
  return [
    `mkdir -p ~/.agentdash`,
    `printf %s '${key}' > ${TOKEN_PATH}`,
    `chmod 600 ${TOKEN_PATH}`,
    `${CONNECT_CLI_BIN} bridge inbox-init ${INBOX_DIR} --server ${origin} --token-file ${TOKEN_PATH}`,
  ].join(" && ");
}

export function ConnectInClaudeOrCodex({
  companyId,
  agentName,
  origin,
}: {
  companyId: string;
  agentName: string;
  origin: string;
}) {
  const queryClient = useQueryClient();
  const [key, setKey] = useState<string | null>(null);
  const [copied, setCopied] = useState<"idle" | "done" | "failed">("idle");

  const endpoints = useQuery({
    queryKey: ["bridge", "me", "endpoints", companyId],
    queryFn: () => bridgeApi.listMyEndpoints(companyId),
    enabled: Boolean(companyId),
  });

  const connected = (endpoints.data?.endpoints ?? []).filter((e) => e.enrolledAt !== null);
  const machine = connected[0] ?? null;

  /**
   * Request and approve in one click. Both halves are the steward's own
   * authority — `approve` accepts the endpoint's owner — so clicking here is
   * the deliberate confirmation the two-step exists to capture, not a bypass
   * of it.
   */
  const generate = useMutation({
    mutationFn: async () => {
      const requested = await bridgeApi.requestEnrollment(companyId, "My laptop");
      const approved = await bridgeApi.approve(companyId, requested.enrollmentId);
      return approved;
    },
    onSuccess: (approved) => {
      setKey(approved.token || null);
      queryClient.invalidateQueries({ queryKey: ["bridge", "me", "endpoints", companyId] });
    },
  });

  const disconnect = useMutation({
    mutationFn: (endpointId: string) => bridgeApi.revoke(companyId, endpointId),
    onSuccess: () => {
      setKey(null);
      queryClient.invalidateQueries({ queryKey: ["bridge", "me", "endpoints", companyId] });
    },
  });

  const setupLine = key ? buildSetupLine(key, origin) : null;

  return (
    <section aria-labelledby="connect-heading" className="rounded-lg border">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-2.5">
        <h2 id="connect-heading" className="text-sm font-semibold">
          Talk to {agentName} from Claude Code or Codex
        </h2>
        {machine ? (
          <span className="text-xs text-muted-foreground">
            <span className="font-medium text-foreground">✓ Connected</span>
            {machine.lastSeenAt ? ` · last seen ${timeAgo(machine.lastSeenAt)}` : null}
          </span>
        ) : null}
      </div>

      <div className="flex flex-col gap-3 px-4 py-4 text-sm">
        <p className="text-muted-foreground">
          You can keep one conversation open for {agentName} in the tool you already work in. It
          shows you what {agentName} has finished, what it is stuck on, and anything waiting for
          your decision — and you answer in the same place.
        </p>

        {machine ? (
          <>
            <div className="rounded-md border bg-muted/30 p-3">
              <p className="font-medium">{machine.label || "This machine"} is connected.</p>
              <p className="mt-1 text-muted-foreground">
                Open the <span className="font-medium">{INBOX_DIR}</span> folder in Claude Code.
                Anything waiting on you appears as the conversation opens. If nothing is waiting,
                you see nothing — that is normal.
              </p>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                disabled={disconnect.isPending}
                onClick={() => disconnect.mutate(machine.id)}
              >
                {disconnect.isPending ? "Disconnecting…" : "Disconnect this machine"}
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={generate.isPending}
                onClick={() => generate.mutate()}
              >
                {generate.isPending ? "Generating…" : "Connect another machine"}
              </Button>
            </div>
          </>
        ) : (
          <div className="rounded-md border border-dashed p-3">
            <p className="font-medium">Not connected yet.</p>
            <p className="mt-1 text-muted-foreground">
              Two steps, once. Nothing to configure afterwards, and no API key of any kind.
            </p>
            <Button
              className="mt-2"
              size="sm"
              disabled={generate.isPending}
              onClick={() => generate.mutate()}
            >
              {generate.isPending ? "Generating…" : "Generate a connection key"}
            </Button>
          </div>
        )}

        {generate.error ? (
          <p className="text-xs text-destructive" role="alert">
            {generate.error instanceof Error
              ? generate.error.message
              : "Could not generate a connection key."}{" "}
            Nothing was connected — try again.
          </p>
        ) : null}

        {setupLine ? (
          <div className="flex flex-col gap-2 rounded-md border p-3">
            <p className="font-medium">Paste this once, on the machine you work on.</p>
            <p className="text-xs text-muted-foreground">
              This is the only thing you will be asked to run. It saves the key and creates the
              folder your conversation lives in.
            </p>
            <pre className="overflow-x-auto rounded border bg-muted/40 p-2.5 text-xs leading-relaxed">
              <code>{setupLine}</code>
            </pre>
            <div className="flex flex-wrap items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={async () => {
                  const ok = await copyToClipboard(setupLine);
                  setCopied(ok ? "done" : "failed");
                }}
              >
                {copied === "done" ? "Copied" : copied === "failed" ? "Copy failed" : "Copy"}
              </Button>
              <span className="text-xs text-muted-foreground">
                Then open <span className="font-medium">{INBOX_DIR}</span> in Claude Code.
              </span>
            </div>
            <p className="text-xs text-muted-foreground">
              <span className="font-medium">This key is shown once.</span> If you lose it, generate
              another — the old one keeps working until you disconnect that machine.
            </p>
          </div>
        ) : null}

        <details className="rounded-md border">
          <summary className="cursor-pointer px-3 py-2 text-sm text-muted-foreground">
            Keeping it up to date, and what each tool can actually do
          </summary>
          <div className="flex flex-col gap-2.5 border-t px-3 py-3 text-sm text-muted-foreground">
            <p>
              Opening the folder is enough. AgentDash never runs a timer of its own and never
              interrupts you — you see what is waiting when you open the conversation.
            </p>

            <p>
              <span className="font-medium text-foreground">Claude Code.</span> Anything waiting
              appears automatically as the conversation opens or resumes. If you want it to look
              again while you work, ask for a repeating check in that same conversation — for
              example, every thirty minutes. Worth knowing before you rely on it: that schedule
              belongs to the conversation, so it goes away if you start a fresh one and lapses after
              about a week; it only runs while Claude Code is open and not busy; and a
              half-hourly check can arrive up to fifteen minutes later than you expect. What happens
              to a check due while the laptop was asleep is not documented anywhere we can point
              to, so treat opening the conversation as the thing you rely on.
            </p>

            <p>
              <span className="font-medium text-foreground">Codex.</span> The automatic
              on-open check is a Claude Code feature and does not apply here — Codex does not read
              it. Codex on the command line has no scheduling of its own at all. Scheduled checks
              exist in the ChatGPT app, where a task set up <span className="italic">inside</span> a
              chat reports back to that chat, while a standalone one opens a new chat each time. A
              task created on ChatGPT on the web cannot reach anything on your own machine, so it
              will not see your inbox.
            </p>

            <p>
              <span className="font-medium text-foreground">Answering.</span> You can always approve
              or decline right here on this page. Doing it from the conversation needs an add-on
              this instance does not publish yet, so until an administrator publishes it, the
              conversation is where you are told and this page is where you decide.
            </p>

            <p>
              <span className="font-medium text-foreground">What to expect.</span> A check with
              nothing new says nothing. Anything still waiting for your decision is mentioned again
              each time you look, because each check reports what is outstanding rather than only
              what changed. After a long gap a big backlog arrives a few at a time.
            </p>
          </div>
        </details>
      </div>
    </section>
  );
}
