// AgentDash — PUBLIC Terms of Service (/terms). No auth, no sidebar, no company
// context. Mounted OUTSIDE CloudAccessGate in ui/src/App.tsx, the same public
// tier as /trial, /pricing, and /investors. Static (no scroll-reveal); built on
// the shared Porcelain legal layout in legal-shared.tsx.
//
// This is TEMPLATE content: a comprehensive, good-faith draft that reflects the
// AgentDash product and the current plan model (Free / Pro $29 per seat / Team
// custom, 14-day no-card trial, $0.05 per run overage). It must be reviewed with
// legal counsel before anyone relies on it, and it carries a clearly-marked
// placeholder for the governing law / jurisdiction.

import {
  LegalPageShell,
  LegalSection,
  List,
  P,
  Placeholder,
  LEGAL_CONTACT_EMAIL,
} from "./legal-shared";

const CLAY = "var(--accent-500)";

export function TermsPage() {
  return (
    <LegalPageShell
      eyebrow="Legal"
      title="Terms of Service"
      intro={
        <>
          These Terms of Service govern your access to and use of AgentDash. By
          creating an account or using the service, you agree to these terms.
          Please read them carefully.
        </>
      }
    >
      <LegalSection title="1. Acceptance and eligibility">
        <P>
          By accessing or using AgentDash, you agree to be bound by these terms. You
          must be at least 18 years old to use the service. If you are using
          AgentDash on behalf of an organization, you represent that you have the
          authority to bind that organization to these terms, and &ldquo;you&rdquo;
          refers to both you and that organization.
        </P>
      </LegalSection>

      <LegalSection title="2. Description of the service">
        <P>
          AgentDash is a multi-human AI workspace in which autonomous AI agents
          perform tasks on your behalf, coordinated by a Chief of Staff agent.
        </P>
        <P>
          <strong className="text-foreground">Important disclaimer about agent output.</strong>{" "}
          Agent outputs and actions are generated by AI and may be inaccurate,
          incomplete, or otherwise unsuitable for your purposes. You are responsible
          for reviewing agent output and for any decisions or actions you take based
          on it. The service is provided without any warranty as to the accuracy,
          quality, or fitness of agent work product. Do not rely on agent output for
          legal, financial, medical, or other professional advice.
        </P>
      </LegalSection>

      <LegalSection title="3. Accounts and security">
        <P>
          You are responsible for maintaining the confidentiality of your account
          credentials and for all activity that occurs under your account. Notify us
          promptly at{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} style={{ color: CLAY, fontWeight: 600 }}>
            {LEGAL_CONTACT_EMAIL}
          </a>{" "}
          if you believe your account has been compromised.
        </P>
      </LegalSection>

      <LegalSection title="4. Subscriptions and billing">
        <P>
          AgentDash currently offers the following plans. This is our current plan
          model and may change:
        </P>
        <List
          items={[
            <><strong className="text-foreground">Free</strong> — no cost; includes a limited number of seats and agent-runs.</>,
            <><strong className="text-foreground">Pro</strong> — $29 per seat per month, with a 14-day trial that requires no credit card.</>,
            <><strong className="text-foreground">Team</strong> — custom pricing for larger operations.</>,
          ]}
        />
        <P>
          Paid subscriptions renew automatically at the end of each billing period
          unless you cancel before renewal. You may cancel at any time, and your plan
          remains active through the end of the period you have paid for. Usage beyond
          your included agent-runs is billed as overage at $0.05 per run. Fees are
          exclusive of taxes, which you are responsible for where applicable. Except
          where required by law, fees are non-refundable, including for partial
          billing periods.
        </P>
      </LegalSection>

      <LegalSection title="5. Acceptable use">
        <P>You agree not to use AgentDash to:</P>
        <List
          items={[
            "Engage in any illegal activity or violate any applicable law or regulation;",
            "Infringe the intellectual property, privacy, or other rights of others;",
            "Transmit malware, attempt to gain unauthorized access, or disrupt the service;",
            "Harass, abuse, or harm others, or generate abusive or deceptive content.",
          ]}
        />
        <P>
          You are responsible for what your agents do through any systems you connect
          to AgentDash, and for ensuring that such use complies with these terms and
          all applicable laws.
        </P>
      </LegalSection>

      <LegalSection title="6. Customer content and intellectual property">
        <P>
          You retain ownership of the content you submit to AgentDash and of the
          outputs that agents generate for you (&ldquo;Customer Content&rdquo;). You
          grant AgentDash a worldwide, non-exclusive license to host, store, process,
          and transmit your Customer Content as necessary to operate and provide the
          service.
        </P>
        <P>
          AgentDash and its licensors own all rights in the platform, software,
          design, and trademarks. Except for the rights expressly granted to you to
          use the service, these terms do not transfer any AgentDash intellectual
          property to you.
        </P>
      </LegalSection>

      <LegalSection title="7. Third-party services and connectors">
        <P>
          AgentDash relies on third-party services — including large language model
          (LLM) providers and any integrations or connectors you enable — to deliver
          its functionality. Your use of those third-party services is governed by
          their own terms and privacy policies, and AgentDash is not responsible for
          their availability, performance, or practices.
        </P>
      </LegalSection>

      <LegalSection title="8. Disclaimers">
        <P>
          The service, including all agent output, is provided &ldquo;AS IS&rdquo;
          and &ldquo;AS AVAILABLE,&rdquo; without warranties of any kind, whether
          express or implied, including warranties of merchantability, fitness for a
          particular purpose, non-infringement, and any warranty as to the accuracy
          or reliability of AI-generated output. We do not warrant that the service
          will be uninterrupted, error-free, or secure.
        </P>
      </LegalSection>

      <LegalSection title="9. Limitation of liability">
        <P>
          To the maximum extent permitted by law, AgentDash and its affiliates,
          officers, employees, and suppliers will not be liable for any indirect,
          incidental, special, consequential, or punitive damages, or for any loss of
          profits, data, or goodwill, arising out of or related to your use of the
          service. Our total aggregate liability for any claim arising out of or
          related to the service will not exceed the amounts you paid to AgentDash in
          the twelve months preceding the event giving rise to the claim.
        </P>
      </LegalSection>

      <LegalSection title="10. Indemnification">
        <P>
          You agree to indemnify and hold harmless AgentDash and its affiliates from
          and against any claims, damages, liabilities, and expenses (including
          reasonable legal fees) arising out of your Customer Content, your use of the
          service, your agents&rsquo; actions through connected systems, or your
          violation of these terms or applicable law.
        </P>
      </LegalSection>

      <LegalSection title="11. Suspension and termination">
        <P>
          We may suspend or terminate your access to the service if you violate these
          terms, if required by law, or to protect the service or other users. You may
          stop using the service and close your account at any time. Provisions that by
          their nature should survive termination — including ownership, disclaimers,
          limitation of liability, and indemnification — will survive.
        </P>
      </LegalSection>

      <LegalSection title="12. Changes to these terms">
        <P>
          We may update these terms from time to time. When we make material changes,
          we will update the &ldquo;Last updated&rdquo; date above and, where
          appropriate, notify you. Your continued use of the service after an update
          means you accept the revised terms.
        </P>
      </LegalSection>

      <LegalSection title="13. Governing law and disputes">
        <P>
          These terms are governed by{" "}
          <Placeholder>[Governing law / jurisdiction — to be completed]</Placeholder>,
          and any disputes arising out of or relating to these terms or the service
          will be resolved in the courts of that jurisdiction, except where applicable
          law provides otherwise.
        </P>
      </LegalSection>

      <LegalSection title="14. Contact us">
        <P>
          If you have questions about these Terms of Service, contact us at{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} style={{ color: CLAY, fontWeight: 600 }}>
            {LEGAL_CONTACT_EMAIL}
          </a>
          .
        </P>
      </LegalSection>
    </LegalPageShell>
  );
}

export default TermsPage;
