import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { doctor } from "../commands/doctor.js";
import { writeConfig } from "../config/store.js";
import type { PaperclipConfig } from "../config/schema.js";

const ORIGINAL_ENV = { ...process.env };

// CI machines and dev hosts routinely occupy port 3199 (a live Paperclip
// server binds exactly that port). Probing a fixed port is therefore an
// ambient-environment dependency, which is what this suite exists to avoid;
// 45937 is an arbitrary high port nothing in the stack claims by default.
const HERMETIC_PORT = 45937;

// The pnpm-install repair lives in commands/worktree.ts and runs a real
// `pnpm install` via child_process. This suite never touches the worktree
// flow, but CI has observed installs hanging or failing inside doctor runs,
// so the module boundary is hardened here: if any code under test ever
// reaches for child_process, the test fails fast and loudly instead of
// doing network I/O from CI.
vi.mock("node:child_process", () => {
  throw new Error(
    "doctor.test.ts is hermetic: child_process use is forbidden under test",
  );
});

function createTempConfig(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "paperclip-doctor-"));
  const configPath = path.join(root, ".paperclip", "config.json");
  const runtimeRoot = path.join(root, "runtime");

  const config: PaperclipConfig = {
    $meta: {
      version: 1,
      updatedAt: "2026-03-10T00:00:00.000Z",
      source: "configure",
    },
    database: {
      mode: "embedded-postgres",
      embeddedPostgresDataDir: path.join(runtimeRoot, "db"),
      embeddedPostgresPort: 55432,
      backup: {
        enabled: true,
        intervalMinutes: 60,
        retentionDays: 30,
        dir: path.join(runtimeRoot, "backups"),
      },
    },
    logging: {
      mode: "file",
      logDir: path.join(runtimeRoot, "logs"),
    },
    server: {
      deploymentMode: "local_trusted",
      exposure: "private",
      host: "127.0.0.1",
      port: HERMETIC_PORT,
      allowedHostnames: [],
      serveUi: true,
    },
    auth: {
      baseUrlMode: "auto",
      disableSignUp: false,
    },
    telemetry: {
      enabled: true,
    },
    storage: {
      provider: "local_disk",
      localDisk: {
        baseDir: path.join(runtimeRoot, "storage"),
      },
      s3: {
        bucket: "paperclip",
        region: "us-east-1",
        prefix: "",
        forcePathStyle: false,
      },
    },
    secrets: {
      provider: "local_encrypted",
      strictMode: false,
      localEncrypted: {
        keyFilePath: path.join(runtimeRoot, "secrets", "master.key"),
      },
    },
  };

  writeConfig(config, configPath);

  // Seed the adjacent .paperclip/.env with the JWT secret so the agent-JWT
  // check passes from fixture data alone. The secret is throwaway test
  // material, not a credential for anything.
  const envFilePath = path.join(root, ".paperclip", ".env");
  fs.writeFileSync(
    envFilePath,
    [
      "# Paperclip environment variables",
      "# Generated by Paperclip CLI commands",
      `PAPERCLIP_AGENT_JWT_SECRET=${"d".repeat(64)}`,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );

  return configPath;
}

describe("doctor", () => {
  beforeEach(() => {
    process.env = { ...ORIGINAL_ENV };
    delete process.env.PAPERCLIP_AGENT_JWT_SECRET;
    delete process.env.PAPERCLIP_SECRETS_MASTER_KEY;
    delete process.env.PAPERCLIP_SECRETS_MASTER_KEY_FILE;
  });

  afterEach(() => {
    process.env = { ...ORIGINAL_ENV };
    vi.restoreAllMocks();
  });

  it("re-runs repairable checks so repaired failures do not remain blocking", async () => {
    const configPath = createTempConfig();

    const summary = await doctor({
      config: configPath,
      repair: true,
      yes: true,
    });

    expect(summary.failed).toBe(0);
    expect(summary.warned).toBe(0);
    // The repair path must hydrate the secret into the live environment
    // (repair -> re-load env file -> re-run check), exercising the
    // repair-rerun logic rather than the ambient environment.
    expect(process.env.PAPERCLIP_AGENT_JWT_SECRET).toBeTruthy();
  });
});
